backendStore:
  databaseMigration: true
  postgres:
    enabled: true
    host: "replace-me"
    port: 5432
    database: "postgres"
    user: "replace-me"
    password: "replace-me"

artifactRoot:
  s3:
    enabled: true
    bucket: "s3://replace-me/path/"
    awsAccessKeyId: "replace-me"
    awsSecretAccessKey: "replace-me"
