apiVersion: v1
kind: Secret
metadata:
  name: mlflow-env-variables
stringData:
  PORT: "8080"
  BACKEND_STORE_URI: postgresql://user:password@host:5432/database # Replace with your creds
  ARTIFACT_ROOT: s3://replace-me/path/ # Replace with your creds
  AWS_ACCESS_KEY_ID: replace-me # Replace with your creds
  AWS_SECRET_ACCESS_KEY: replace-me # Replace with your creds
